ML_config:
  model_args:
    num_classes: 10
  train_config:
    epochs: 3
    lr: 0.0001
    train_bs: 64
  test_config:
    test_bs: 64
  initial_model_path: initial_models
  dataset_dir: ./CIFAR10_dirichlet0.05_12
  dataset_id: CIFAR10_dirichlet0.05_12
  model_file_path: models/CNN.py
  model_id: CNN_model

FL_config:
  Agg_algo: fedavg
  Agg_args: None
  CS_algo: smart_v1
  CS_args: None
  clients_per_round: 3
  total_num_clients: 12
  total_rounds: 20

client_config:
  minibatch_time: 0.81

server_config:
  test_bs: 64
  seed: 1201
  use_gpu: true
  save_path: ../results
